// This module contains generated protobuf code
// The files are generated by build.rs during compilation

// Common types
pub mod common {
    tonic::include_proto!("common");
}

// Trading service
pub mod trading {
    tonic::include_proto!("trading");
}

// Pricing service
pub mod pricing {
    tonic::include_proto!("pricing");
}

// Re-export commonly used types
pub use common::{Side, OrderType, RejectReason, Timestamp};
pub use trading::{
    trading_service_server::{TradingService, TradingServiceServer},
    trading_service_client::TradingServiceClient,
    *,
};
pub use pricing::{
    pricing_service_server::{PricingService, PricingServiceServer},
    pricing_service_client::PricingServiceClient,
    *,
};
