// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SimulationConfig {
    #[prost(uint64, tag = "1")]
    pub num_simulations: u64,
    #[prost(uint64, tag = "2")]
    pub num_steps: u64,
    #[prost(uint64, tag = "3")]
    pub seed: u64,
    #[prost(bool, tag = "4")]
    pub antithetic_enabled: bool,
    #[prost(bool, tag = "5")]
    pub control_variates_enabled: bool,
    #[prost(bool, tag = "6")]
    pub stratified_sampling_enabled: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EuropeanRequest {
    #[prost(double, tag = "1")]
    pub spot: f64,
    #[prost(double, tag = "2")]
    pub strike: f64,
    #[prost(double, tag = "3")]
    pub rate: f64,
    #[prost(double, tag = "4")]
    pub volatility: f64,
    #[prost(double, tag = "5")]
    pub time_to_maturity: f64,
    #[prost(message, optional, tag = "6")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AmericanRequest {
    #[prost(double, tag = "1")]
    pub spot: f64,
    #[prost(double, tag = "2")]
    pub strike: f64,
    #[prost(double, tag = "3")]
    pub rate: f64,
    #[prost(double, tag = "4")]
    pub volatility: f64,
    #[prost(double, tag = "5")]
    pub time_to_maturity: f64,
    #[prost(uint32, tag = "6")]
    pub num_exercise_points: u32,
    #[prost(message, optional, tag = "7")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AsianRequest {
    #[prost(double, tag = "1")]
    pub spot: f64,
    #[prost(double, tag = "2")]
    pub strike: f64,
    #[prost(double, tag = "3")]
    pub rate: f64,
    #[prost(double, tag = "4")]
    pub volatility: f64,
    #[prost(double, tag = "5")]
    pub time_to_maturity: f64,
    #[prost(uint32, tag = "6")]
    pub num_observations: u32,
    #[prost(message, optional, tag = "7")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BarrierRequest {
    #[prost(double, tag = "1")]
    pub spot: f64,
    #[prost(double, tag = "2")]
    pub strike: f64,
    #[prost(double, tag = "3")]
    pub rate: f64,
    #[prost(double, tag = "4")]
    pub volatility: f64,
    #[prost(double, tag = "5")]
    pub time_to_maturity: f64,
    #[prost(double, tag = "6")]
    pub barrier_level: f64,
    #[prost(enumeration = "BarrierType", tag = "7")]
    pub barrier_type: i32,
    #[prost(double, tag = "8")]
    pub rebate: f64,
    #[prost(message, optional, tag = "9")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LookbackRequest {
    #[prost(double, tag = "1")]
    pub spot: f64,
    #[prost(double, tag = "2")]
    pub strike: f64,
    #[prost(double, tag = "3")]
    pub rate: f64,
    #[prost(double, tag = "4")]
    pub volatility: f64,
    #[prost(double, tag = "5")]
    pub time_to_maturity: f64,
    #[prost(bool, tag = "6")]
    pub fixed_strike: bool,
    #[prost(message, optional, tag = "7")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BermudanRequest {
    #[prost(double, tag = "1")]
    pub spot: f64,
    #[prost(double, tag = "2")]
    pub strike: f64,
    #[prost(double, tag = "3")]
    pub rate: f64,
    #[prost(double, tag = "4")]
    pub volatility: f64,
    #[prost(double, repeated, tag = "5")]
    pub exercise_dates: ::prost::alloc::vec::Vec<f64>,
    #[prost(message, optional, tag = "6")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketPriceRequest {
    /// e.g., "AAPL"
    #[prost(string, tag = "1")]
    pub underlying_symbol: ::prost::alloc::string::String,
    /// "CALL" or "PUT"
    #[prost(string, tag = "2")]
    pub option_type: ::prost::alloc::string::String,
    /// "EUROPEAN", "AMERICAN", "ASIAN", etc.
    #[prost(string, tag = "3")]
    pub option_style: ::prost::alloc::string::String,
    #[prost(double, tag = "4")]
    pub strike: f64,
    #[prost(double, tag = "5")]
    pub time_to_maturity: f64,
    /// Market data will be fetched from order book
    /// Volatility can be provided or implied
    ///
    /// Optional - will estimate if 0
    #[prost(double, tag = "6")]
    pub volatility: f64,
    /// Risk-free rate
    #[prost(double, tag = "7")]
    pub rate: f64,
    #[prost(message, optional, tag = "8")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceResponse {
    #[prost(double, tag = "1")]
    pub price: f64,
    #[prost(double, tag = "2")]
    pub computation_time_ms: f64,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
    /// Additional Greeks (optional)
    #[prost(double, optional, tag = "4")]
    pub delta: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "5")]
    pub gamma: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "6")]
    pub vega: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "7")]
    pub theta: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "8")]
    pub rho: ::core::option::Option<f64>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchRequest {
    #[prost(message, repeated, tag = "1")]
    pub european_calls: ::prost::alloc::vec::Vec<EuropeanRequest>,
    #[prost(message, repeated, tag = "2")]
    pub european_puts: ::prost::alloc::vec::Vec<EuropeanRequest>,
    #[prost(message, optional, tag = "3")]
    pub config: ::core::option::Option<SimulationConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchResponse {
    #[prost(double, repeated, tag = "1")]
    pub european_call_prices: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, repeated, tag = "2")]
    pub european_put_prices: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, tag = "3")]
    pub total_computation_time_ms: f64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BarrierType {
    UpAndOut = 0,
    UpAndIn = 1,
    DownAndOut = 2,
    DownAndIn = 3,
}
impl BarrierType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            BarrierType::UpAndOut => "UP_AND_OUT",
            BarrierType::UpAndIn => "UP_AND_IN",
            BarrierType::DownAndOut => "DOWN_AND_OUT",
            BarrierType::DownAndIn => "DOWN_AND_IN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UP_AND_OUT" => Some(Self::UpAndOut),
            "UP_AND_IN" => Some(Self::UpAndIn),
            "DOWN_AND_OUT" => Some(Self::DownAndOut),
            "DOWN_AND_IN" => Some(Self::DownAndIn),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod pricing_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Pricing Service - Monte Carlo options pricing via FFI to C library
    #[derive(Debug, Clone)]
    pub struct PricingServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PricingServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PricingServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PricingServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            PricingServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// European Options
        pub async fn price_european_call(
            &mut self,
            request: impl tonic::IntoRequest<super::EuropeanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceEuropeanCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceEuropeanCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn price_european_put(
            &mut self,
            request: impl tonic::IntoRequest<super::EuropeanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceEuropeanPut",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceEuropeanPut"));
            self.inner.unary(req, path, codec).await
        }
        /// American Options
        pub async fn price_american_call(
            &mut self,
            request: impl tonic::IntoRequest<super::AmericanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceAmericanCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceAmericanCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn price_american_put(
            &mut self,
            request: impl tonic::IntoRequest<super::AmericanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceAmericanPut",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceAmericanPut"));
            self.inner.unary(req, path, codec).await
        }
        /// Asian Options
        pub async fn price_asian_call(
            &mut self,
            request: impl tonic::IntoRequest<super::AsianRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceAsianCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceAsianCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn price_asian_put(
            &mut self,
            request: impl tonic::IntoRequest<super::AsianRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceAsianPut",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceAsianPut"));
            self.inner.unary(req, path, codec).await
        }
        /// Barrier Options
        pub async fn price_barrier_call(
            &mut self,
            request: impl tonic::IntoRequest<super::BarrierRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceBarrierCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceBarrierCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn price_barrier_put(
            &mut self,
            request: impl tonic::IntoRequest<super::BarrierRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceBarrierPut",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceBarrierPut"));
            self.inner.unary(req, path, codec).await
        }
        /// Lookback Options
        pub async fn price_lookback_call(
            &mut self,
            request: impl tonic::IntoRequest<super::LookbackRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceLookbackCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceLookbackCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn price_lookback_put(
            &mut self,
            request: impl tonic::IntoRequest<super::LookbackRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceLookbackPut",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceLookbackPut"));
            self.inner.unary(req, path, codec).await
        }
        /// Bermudan Options
        pub async fn price_bermudan_call(
            &mut self,
            request: impl tonic::IntoRequest<super::BermudanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceBermudanCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceBermudanCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn price_bermudan_put(
            &mut self,
            request: impl tonic::IntoRequest<super::BermudanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceBermudanPut",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceBermudanPut"));
            self.inner.unary(req, path, codec).await
        }
        /// Batch pricing for portfolios
        pub async fn price_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchRequest>,
        ) -> std::result::Result<tonic::Response<super::BatchResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceBatch"));
            self.inner.unary(req, path, codec).await
        }
        /// NEW: Price an option based on current market data
        pub async fn price_from_market(
            &mut self,
            request: impl tonic::IntoRequest<super::MarketPriceRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pricing.PricingService/PriceFromMarket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pricing.PricingService", "PriceFromMarket"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod pricing_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PricingServiceServer.
    #[async_trait]
    pub trait PricingService: Send + Sync + 'static {
        /// European Options
        async fn price_european_call(
            &self,
            request: tonic::Request<super::EuropeanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        async fn price_european_put(
            &self,
            request: tonic::Request<super::EuropeanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        /// American Options
        async fn price_american_call(
            &self,
            request: tonic::Request<super::AmericanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        async fn price_american_put(
            &self,
            request: tonic::Request<super::AmericanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        /// Asian Options
        async fn price_asian_call(
            &self,
            request: tonic::Request<super::AsianRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        async fn price_asian_put(
            &self,
            request: tonic::Request<super::AsianRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        /// Barrier Options
        async fn price_barrier_call(
            &self,
            request: tonic::Request<super::BarrierRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        async fn price_barrier_put(
            &self,
            request: tonic::Request<super::BarrierRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        /// Lookback Options
        async fn price_lookback_call(
            &self,
            request: tonic::Request<super::LookbackRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        async fn price_lookback_put(
            &self,
            request: tonic::Request<super::LookbackRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        /// Bermudan Options
        async fn price_bermudan_call(
            &self,
            request: tonic::Request<super::BermudanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        async fn price_bermudan_put(
            &self,
            request: tonic::Request<super::BermudanRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
        /// Batch pricing for portfolios
        async fn price_batch(
            &self,
            request: tonic::Request<super::BatchRequest>,
        ) -> std::result::Result<tonic::Response<super::BatchResponse>, tonic::Status>;
        /// NEW: Price an option based on current market data
        async fn price_from_market(
            &self,
            request: tonic::Request<super::MarketPriceRequest>,
        ) -> std::result::Result<tonic::Response<super::PriceResponse>, tonic::Status>;
    }
    /// Pricing Service - Monte Carlo options pricing via FFI to C library
    #[derive(Debug)]
    pub struct PricingServiceServer<T: PricingService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: PricingService> PricingServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PricingServiceServer<T>
    where
        T: PricingService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/pricing.PricingService/PriceEuropeanCall" => {
                    #[allow(non_camel_case_types)]
                    struct PriceEuropeanCallSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::EuropeanRequest>
                    for PriceEuropeanCallSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EuropeanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_european_call(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceEuropeanCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceEuropeanPut" => {
                    #[allow(non_camel_case_types)]
                    struct PriceEuropeanPutSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::EuropeanRequest>
                    for PriceEuropeanPutSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EuropeanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_european_put(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceEuropeanPutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceAmericanCall" => {
                    #[allow(non_camel_case_types)]
                    struct PriceAmericanCallSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::AmericanRequest>
                    for PriceAmericanCallSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AmericanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_american_call(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceAmericanCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceAmericanPut" => {
                    #[allow(non_camel_case_types)]
                    struct PriceAmericanPutSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::AmericanRequest>
                    for PriceAmericanPutSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AmericanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_american_put(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceAmericanPutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceAsianCall" => {
                    #[allow(non_camel_case_types)]
                    struct PriceAsianCallSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::AsianRequest>
                    for PriceAsianCallSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AsianRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_asian_call(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceAsianCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceAsianPut" => {
                    #[allow(non_camel_case_types)]
                    struct PriceAsianPutSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::AsianRequest>
                    for PriceAsianPutSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AsianRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_asian_put(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceAsianPutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceBarrierCall" => {
                    #[allow(non_camel_case_types)]
                    struct PriceBarrierCallSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::BarrierRequest>
                    for PriceBarrierCallSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BarrierRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_barrier_call(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceBarrierCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceBarrierPut" => {
                    #[allow(non_camel_case_types)]
                    struct PriceBarrierPutSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::BarrierRequest>
                    for PriceBarrierPutSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BarrierRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_barrier_put(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceBarrierPutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceLookbackCall" => {
                    #[allow(non_camel_case_types)]
                    struct PriceLookbackCallSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::LookbackRequest>
                    for PriceLookbackCallSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LookbackRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_lookback_call(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceLookbackCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceLookbackPut" => {
                    #[allow(non_camel_case_types)]
                    struct PriceLookbackPutSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::LookbackRequest>
                    for PriceLookbackPutSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LookbackRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_lookback_put(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceLookbackPutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceBermudanCall" => {
                    #[allow(non_camel_case_types)]
                    struct PriceBermudanCallSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::BermudanRequest>
                    for PriceBermudanCallSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BermudanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_bermudan_call(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceBermudanCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceBermudanPut" => {
                    #[allow(non_camel_case_types)]
                    struct PriceBermudanPutSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::BermudanRequest>
                    for PriceBermudanPutSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BermudanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_bermudan_put(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceBermudanPutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceBatch" => {
                    #[allow(non_camel_case_types)]
                    struct PriceBatchSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::BatchRequest>
                    for PriceBatchSvc<T> {
                        type Response = super::BatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_batch(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pricing.PricingService/PriceFromMarket" => {
                    #[allow(non_camel_case_types)]
                    struct PriceFromMarketSvc<T: PricingService>(pub Arc<T>);
                    impl<
                        T: PricingService,
                    > tonic::server::UnaryService<super::MarketPriceRequest>
                    for PriceFromMarketSvc<T> {
                        type Response = super::PriceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MarketPriceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingService>::price_from_market(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = PriceFromMarketSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: PricingService> Clone for PricingServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: PricingService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: PricingService> tonic::server::NamedService for PricingServiceServer<T> {
        const NAME: &'static str = "pricing.PricingService";
    }
}
