// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub user_id: u64,
    #[prost(enumeration = "super::common::Side", tag = "3")]
    pub side: i32,
    #[prost(enumeration = "super::common::OrderType", tag = "4")]
    pub order_type: i32,
    /// Price in dollars (will be converted to cents)
    #[prost(double, tag = "5")]
    pub price: f64,
    #[prost(uint64, tag = "6")]
    pub quantity: u64,
    /// Optional - will be generated if not provided
    #[prost(uint64, tag = "7")]
    pub client_order_id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderResponse {
    #[prost(uint64, tag = "1")]
    pub client_order_id: u64,
    #[prost(uint64, tag = "2")]
    pub exchange_order_id: u64,
    #[prost(bool, tag = "3")]
    pub accepted: bool,
    #[prost(enumeration = "super::common::RejectReason", tag = "4")]
    pub reject_reason: i32,
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub user_id: u64,
    #[prost(uint64, tag = "3")]
    pub client_order_id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelResponse {
    #[prost(uint64, tag = "1")]
    pub client_order_id: u64,
    #[prost(bool, tag = "2")]
    pub cancelled: bool,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    /// Optional - for filtering user-specific events
    #[prost(uint64, tag = "2")]
    pub user_id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionReport {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub client_order_id: u64,
    #[prost(uint64, tag = "3")]
    pub exchange_order_id: u64,
    #[prost(uint64, tag = "4")]
    pub execution_id: u64,
    #[prost(uint64, tag = "5")]
    pub user_id: u64,
    #[prost(enumeration = "super::common::Side", tag = "6")]
    pub side: i32,
    #[prost(double, tag = "7")]
    pub fill_price: f64,
    #[prost(uint64, tag = "8")]
    pub fill_quantity: u64,
    #[prost(uint64, tag = "9")]
    pub leaves_quantity: u64,
    #[prost(message, optional, tag = "10")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeReport {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub trade_id: u64,
    #[prost(double, tag = "3")]
    pub price: f64,
    #[prost(uint64, tag = "4")]
    pub quantity: u64,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookSnapshot {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub bids: ::prost::alloc::vec::Vec<PriceLevel>,
    #[prost(message, repeated, tag = "3")]
    pub asks: ::prost::alloc::vec::Vec<PriceLevel>,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
    /// For gap detection
    #[prost(uint32, tag = "5")]
    pub sequence: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PriceLevel {
    #[prost(double, tag = "1")]
    pub price: f64,
    #[prost(uint64, tag = "2")]
    pub quantity: u64,
    /// Number of orders at this level
    #[prost(uint32, tag = "3")]
    pub order_count: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBookRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    /// Number of levels (0 = all)
    #[prost(uint32, tag = "2")]
    pub depth: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderStatusRequest {
    #[prost(uint64, tag = "1")]
    pub client_order_id: u64,
    #[prost(uint64, tag = "2")]
    pub user_id: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderStatusResponse {
    #[prost(uint64, tag = "1")]
    pub client_order_id: u64,
    #[prost(uint64, tag = "2")]
    pub exchange_order_id: u64,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(enumeration = "super::common::Side", tag = "4")]
    pub side: i32,
    #[prost(double, tag = "5")]
    pub price: f64,
    #[prost(uint64, tag = "6")]
    pub original_quantity: u64,
    #[prost(uint64, tag = "7")]
    pub filled_quantity: u64,
    #[prost(uint64, tag = "8")]
    pub remaining_quantity: u64,
    /// "OPEN", "FILLED", "CANCELLED", "REJECTED"
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
/// Generated client implementations.
pub mod trading_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Trading Service - handles order submission and market data
    #[derive(Debug, Clone)]
    pub struct TradingServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TradingServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TradingServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TradingServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            TradingServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Order operations
        pub async fn submit_order(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/trading.TradingService/SubmitOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("trading.TradingService", "SubmitOrder"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/trading.TradingService/CancelOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("trading.TradingService", "CancelOrder"));
            self.inner.unary(req, path, codec).await
        }
        /// Market data streams
        pub async fn stream_executions(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ExecutionReport>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/trading.TradingService/StreamExecutions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("trading.TradingService", "StreamExecutions"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn stream_order_book(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::OrderBookSnapshot>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/trading.TradingService/StreamOrderBook",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("trading.TradingService", "StreamOrderBook"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn stream_trades(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TradeReport>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/trading.TradingService/StreamTrades",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("trading.TradingService", "StreamTrades"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Query operations
        pub async fn get_order_book(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderBookRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OrderBookSnapshot>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/trading.TradingService/GetOrderBook",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("trading.TradingService", "GetOrderBook"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_order_status(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OrderStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/trading.TradingService/GetOrderStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("trading.TradingService", "GetOrderStatus"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod trading_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TradingServiceServer.
    #[async_trait]
    pub trait TradingService: Send + Sync + 'static {
        /// Order operations
        async fn submit_order(
            &self,
            request: tonic::Request<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status>;
        async fn cancel_order(
            &self,
            request: tonic::Request<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status>;
        /// Server streaming response type for the StreamExecutions method.
        type StreamExecutionsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ExecutionReport, tonic::Status>,
            >
            + Send
            + 'static;
        /// Market data streams
        async fn stream_executions(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamExecutionsStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamOrderBook method.
        type StreamOrderBookStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::OrderBookSnapshot, tonic::Status>,
            >
            + Send
            + 'static;
        async fn stream_order_book(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamOrderBookStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamTrades method.
        type StreamTradesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TradeReport, tonic::Status>,
            >
            + Send
            + 'static;
        async fn stream_trades(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamTradesStream>,
            tonic::Status,
        >;
        /// Query operations
        async fn get_order_book(
            &self,
            request: tonic::Request<super::OrderBookRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OrderBookSnapshot>,
            tonic::Status,
        >;
        async fn get_order_status(
            &self,
            request: tonic::Request<super::OrderStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OrderStatusResponse>,
            tonic::Status,
        >;
    }
    /// Trading Service - handles order submission and market data
    #[derive(Debug)]
    pub struct TradingServiceServer<T: TradingService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: TradingService> TradingServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TradingServiceServer<T>
    where
        T: TradingService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/trading.TradingService/SubmitOrder" => {
                    #[allow(non_camel_case_types)]
                    struct SubmitOrderSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::OrderRequest>
                    for SubmitOrderSvc<T> {
                        type Response = super::OrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::submit_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SubmitOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/trading.TradingService/CancelOrder" => {
                    #[allow(non_camel_case_types)]
                    struct CancelOrderSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::CancelRequest>
                    for CancelOrderSvc<T> {
                        type Response = super::CancelResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::cancel_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CancelOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/trading.TradingService/StreamExecutions" => {
                    #[allow(non_camel_case_types)]
                    struct StreamExecutionsSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::ServerStreamingService<super::StreamRequest>
                    for StreamExecutionsSvc<T> {
                        type Response = super::ExecutionReport;
                        type ResponseStream = T::StreamExecutionsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::stream_executions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamExecutionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/trading.TradingService/StreamOrderBook" => {
                    #[allow(non_camel_case_types)]
                    struct StreamOrderBookSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::ServerStreamingService<super::StreamRequest>
                    for StreamOrderBookSvc<T> {
                        type Response = super::OrderBookSnapshot;
                        type ResponseStream = T::StreamOrderBookStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::stream_order_book(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamOrderBookSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/trading.TradingService/StreamTrades" => {
                    #[allow(non_camel_case_types)]
                    struct StreamTradesSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::ServerStreamingService<super::StreamRequest>
                    for StreamTradesSvc<T> {
                        type Response = super::TradeReport;
                        type ResponseStream = T::StreamTradesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::stream_trades(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamTradesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/trading.TradingService/GetOrderBook" => {
                    #[allow(non_camel_case_types)]
                    struct GetOrderBookSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::OrderBookRequest>
                    for GetOrderBookSvc<T> {
                        type Response = super::OrderBookSnapshot;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderBookRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::get_order_book(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetOrderBookSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/trading.TradingService/GetOrderStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetOrderStatusSvc<T: TradingService>(pub Arc<T>);
                    impl<
                        T: TradingService,
                    > tonic::server::UnaryService<super::OrderStatusRequest>
                    for GetOrderStatusSvc<T> {
                        type Response = super::OrderStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TradingService>::get_order_status(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetOrderStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: TradingService> Clone for TradingServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: TradingService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: TradingService> tonic::server::NamedService for TradingServiceServer<T> {
        const NAME: &'static str = "trading.TradingService";
    }
}
